git:
  depth: 10
language: node_js
node_js: '12'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install --frozen-lockfile --ignore-engines
before_script:
  - yarn run build
jobs:
  fast_finish: true
  include:
    - name: Test
      script: yarn run jest -w 4
    - name: Lint
      script: yarn run lint
cache:
  yarn: true
after_script: 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
