git:
  depth: 10
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
install:
  - "npm install"
  - "travis_wait npm run install"
after_script: "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
