enableGlobalCache: false

nodeLinker: node-modules

logFilters:
  - pattern: "* doesn't provide react (*)*"
    level: "discard"
  - pattern: "* doesn't provide react-dom (*)*"
    level: "discard"
  - pattern: "* doesn't provide @react-spring/web (*)*"
    level: "discard"
  - pattern: "* doesn't provide webpack (*)*"
    level: "discard"
  - pattern: "Some peer dependencies are incorrectly met*"
    level: "discard"
