import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    projects: [
      'packages/visx-scale/vitest.config.ts',
      'packages/visx-point/vitest.config.ts',
      'packages/visx-curve/vitest.config.ts',
      'packages/visx-event/vitest.config.ts',
      'packages/visx-mock-data/vitest.config.ts',
      'packages/visx-stats/vitest.config.ts',
      'packages/visx-delaunay/vitest.config.ts',
      'packages/visx-voronoi/vitest.config.ts',
      'packages/visx-drag/vitest.config.ts',
      'packages/visx-network/vitest.config.ts',
      'packages/visx-threshold/vitest.config.ts',
      'packages/visx-group/vitest.config.ts',
      'packages/visx-pattern/vitest.config.ts',
      'packages/visx-clip-path/vitest.config.ts',
      'packages/visx-zoom/vitest.config.ts',
      'packages/visx-grid/vitest.config.ts',
      'packages/visx-marker/vitest.config.ts',
      'packages/visx-gradient/vitest.config.ts',
      'packages/visx-glyph/vitest.config.ts',
      'packages/visx-tooltip/vitest.config.ts',
      'packages/visx-chord/vitest.config.ts',
      'packages/visx-responsive/vitest.config.ts',
      'packages/visx-annotation/vitest.config.ts',
      'packages/visx-axis/vitest.config.ts',
      'packages/visx-legend/vitest.config.ts',
      'packages/visx-bounds/vitest.config.ts',
      'packages/visx-brush/vitest.config.ts',
      'packages/visx-geo/vitest.config.ts',
      'packages/visx-heatmap/vitest.config.ts',
      'packages/visx-hierarchy/vitest.config.ts',
      'packages/visx-react-spring/vitest.config.ts',
      'packages/visx-sankey/vitest.config.ts',
      'packages/visx-shape/vitest.config.ts',
      'packages/visx-text/vitest.config.ts',
      'packages/visx-wordcloud/vitest.config.ts',
      'packages/visx-xychart/vitest.config.ts',
      'packages/visx-visx/vitest.config.ts',
      'packages/visx-vendor/vitest.config.ts',
    ],
  },
});
