export type ChartType =
  | 'line'
  | 'bar'
  | 'scatter'
  | 'area'
  | 'pie'
  | 'donut'
  | 'histogram'
  | 'heatmap';

export type ChartA11yValue = string | number | Date;

export type ChartA11yAccessor<Datum, Value = ChartA11yValue> = (
  datum: Datum,
  index: number,
  data: readonly Datum[],
) => Value;

export type ChartA11yFormatter<Value = unknown> = (value: Value) => string;

export type ChartA11ySeriesConfig<Datum> = {
  label: string | ((seriesIndex: number) => string);
  data?: readonly Datum[];
};

export type ChartA11yFocusedPoint<Datum> = {
  seriesIndex: number;
  index: number;
  datum: Datum;
};

export type ChartA11yIds = {
  rootId: string;
  descriptionId: string;
  tableId: string;
};

export type ChartA11ySvgProps = {
  role: 'graphics-document';
  'aria-roledescription': string;
  'aria-label': string;
  'aria-describedby': string;
};

export type ChartA11ySeriesProps = {
  role: 'graphics-object';
  'aria-roledescription': string;
  'aria-label': string;
};

export type ChartA11yPointProps = {
  role: 'graphics-symbol';
  'aria-roledescription': string;
  'aria-label': string;
};

export type ChartA11yProps = {
  ids: ChartA11yIds;
  svg: ChartA11ySvgProps;
  series: ChartA11ySeriesProps[];
  points: ChartA11yPointProps[][];
};

export type A11yLocale = {
  chartRoleDescription: string;
  seriesRoleDescription: string;
  pointRoleDescription: string;
  chartTypes: Partial<Record<ChartType, string>>;
  dataTableCaption: (title: string) => string;
  keyboardHelp: string;
};

type ChartA11yBaseConfig<Datum> = {
  /** Stable id for generated description, table, and live-region relationships. */
  id?: string;
  /** Prefix used when an id is generated by client or server helpers. */
  idPrefix?: string;
  title: string;
  x: ChartA11yAccessor<Datum>;
  y: ChartA11yAccessor<Datum, number>;
  xLabel?: string;
  yLabel?: string;
  description?: string;
  chartType?: ChartType;
  formatX?: ChartA11yFormatter;
  formatY?: ChartA11yFormatter<number>;
  pointDescriptionThreshold?: number;
  dataTableEnabled?: boolean;
  keyboardNavEnabled?: boolean;
  onPointFocus?: (point: ChartA11yFocusedPoint<Datum>) => void;
  locale?: Partial<A11yLocale>;
};

export type ChartA11yFlatConfig<Datum> = ChartA11yBaseConfig<Datum> & {
  data: readonly Datum[];
  series?: readonly ChartA11ySeriesConfig<Datum>[];
};

export type ChartA11yNestedConfig<Datum> = ChartA11yBaseConfig<Datum> & {
  data: readonly (readonly Datum[])[];
  series: readonly [ChartA11ySeriesConfig<Datum>, ...ChartA11ySeriesConfig<Datum>[]];
};

export type ChartA11yConfig<Datum> = ChartA11yFlatConfig<Datum> | ChartA11yNestedConfig<Datum>;
