import {
  curveBasis,
  curveBasisClosed,
  curveBasisOpen,
  curveStep,
  curveStepAfter,
  curveStepbefore,
  curveBundle,
  curveLinear,
  curveLinearClosed,
  curveCardinal,
  curveCardinalClosed,
  curveCardinalOpen,
  curveCatmullRom,
  curveCatmullRomClosed,
  curveCatmullRomOpen,
  curveMonotoneX,
  curveMonotoneY,
  curveNatural,
} from 'd3-shape';

export default {
  basis: curveBasis,
  basisClose: curveBasisClosed,
  basisOpen: curveBasisOpen,
  step: curveStep,
  stepAfter: curveStepAfter,
  stepBefore: curveStepbefore,
  bundle: curveBundle,
  linear: curveLinear,
  linearClosed: curveLinearClosed,
  monotoneX: curveMonotoneX,
  monotoneY: curveMonotoneY,
  cardinal: curveCardinal,
  cardinalClosed: curveCardinalClosed,
  cardinalOpen: curveCardinalOpen,
  catmullRom: curveCatmullRom,
  catmullRomClosed: curveCatmullRomClosed,
  catmullRomOpen: curveCatmullRomOpen,
  natural: curveNatural,
};
