"use strict";

exports.__esModule = true;
exports.XYCHART_EVENT_SOURCE = exports.LINESERIES_EVENT_SOURCE = exports.GLYPHSERIES_EVENT_SOURCE = exports.BARSTACK_EVENT_SOURCE = exports.BARSERIES_EVENT_SOURCE = exports.BARGROUP_EVENT_SOURCE = exports.AREASTACK_EVENT_SOURCE = exports.AREASERIES_EVENT_SOURCE = void 0;
// event sources
var AREASERIES_EVENT_SOURCE = 'AREASERIES_EVENT_SOURCE';
exports.AREASERIES_EVENT_SOURCE = AREASERIES_EVENT_SOURCE;
var AREASTACK_EVENT_SOURCE = 'AREASTACK_EVENT_SOURCE';
exports.AREASTACK_EVENT_SOURCE = AREASTACK_EVENT_SOURCE;
var BARGROUP_EVENT_SOURCE = 'BARGROUP_EVENT_SOURCE';
exports.BARGROUP_EVENT_SOURCE = BARGROUP_EVENT_SOURCE;
var BARSERIES_EVENT_SOURCE = 'BARSERIES_EVENT_SOURCE';
exports.BARSERIES_EVENT_SOURCE = BARSERIES_EVENT_SOURCE;
var BARSTACK_EVENT_SOURCE = 'BARSTACK_EVENT_SOURCE';
exports.BARSTACK_EVENT_SOURCE = BARSTACK_EVENT_SOURCE;
var GLYPHSERIES_EVENT_SOURCE = 'GLYPHSERIES_EVENT_SOURCE';
exports.GLYPHSERIES_EVENT_SOURCE = GLYPHSERIES_EVENT_SOURCE;
var LINESERIES_EVENT_SOURCE = 'LINESERIES_EVENT_SOURCE';
exports.LINESERIES_EVENT_SOURCE = LINESERIES_EVENT_SOURCE;
var XYCHART_EVENT_SOURCE = 'XYCHART_EVENT_SOURCE';
exports.XYCHART_EVENT_SOURCE = XYCHART_EVENT_SOURCE;